### ISSUE TITLE
Bad typescript descriptor

### ISSUE THREAD

**Issue by pokornyib** [NordicSemiconductor/pc-ble-driver-js#128]
The typescript descriptor file contains wrong function header:
`performDfu(zipFilePath: string, callback: (err?: any, abort?: boolean) => void): void;`
but in the .js files exits:
`performDFU(zipFilePath, callback)`

**Comment by IvanSanchez** [comment]
Oh, do you mean a lowercase/uppercase problem between `Dfu` and `DFU`? I can see how that was easily overlooked.

Would you be so kind as to propose a pull request to fix the typo in the typescript defs? That'd make this be fixed faster.

**Comment by pokornyib** [comment]
Done.
