### ISSUE TITLE
Unable to connect using non-SEGGER USB to serial adapters.

### ISSUE THREAD

**Issue by electronut** [NordicSemiconductor/pc-ble-driver-js#146]
The pc-ble-driver [documentation](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/Installation.md) says:

> This communication library works over any kind of serial port (UART), but it is most often used over a Segger J-Link USB CDC UART. 

But see the code below from:

https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/src/serialadapter_osx.cpp

```
for (auto device : *devices)
    {
        if ((strcmp(device->manufacturer,"SEGGER") == 0)
            || (strcasecmp(device->manufacturer, "arm") == 0)
            || (strcasecmp(device->manufacturer, "mbed") == 0))

```

It seems to be filtering for SEGGER.

I am unable to get the heart_rate_collector example work with a non-SEGGER USB to serial adapter. Can this issue be addressed? Thanks.

**Comment by pokornyib** [comment]
I solved this issue with new function: createCustomAdapter(),  it is merged already to master, but didn't published on npm
