### ISSUE TITLE
query - "This will work as long as precompiled binaries exist for your platform/runtime environment, ref. the files attached to the Releases"

### ISSUE THREAD

**Issue by tonykappen** [NordicSemiconductor/pc-ble-driver-js#148]
Hi, 

I am a newbie to embedded development. I am well versed with java script. I am under the impression nordic allows you to communicate with java script to the development kit. I have a nRF52 (nRF52832) development kit (PCA10040). I am trying to installing the pc-ble-driver-js from the link https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/Installation.md. I wish to develop the javascript application with electron. I didnot understand the portion of the text "This will work as long as precompiled binaries exist for your platform/runtime environment, ref. the files attached to the Releases". Can you please give me further explanation on the meaning of the line. I am developing on 64bit Windows 10 OS with a 32bit version of node installed. Your help is much appreciated. 

Sincerely,

Tony.

**Comment by tonykappen** [comment]
Thank you for helping me out. I think pc-ble-driver-js got installed. When I tried to run heart rate monitor example I got the error as shown in the below screen shot
![image](https://user-images.githubusercontent.com/4988857/38041231-d886e12c-3276-11e8-8ced-5a946c89dd4d.png)

Can you please help me out?

**Comment by bencefr** [comment]
Hi @tonykappen ,
Sorry for the delay, Easter in Norway is really long :)
Judging by the picture you have an incorrect firmware on the device, meaning one that runs with different baudrate than expected. I might be wrong, but it doesn't hurt to try to either modify the example source to match the baudrate of the firmware or flash the correct firmware.
You have the choice of 115200 and 1000000, follow the guide [here](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/Installation.md#hardware-setup).

**Comment by tonykappen** [comment]
I also tried flashing the pc-ble-driver with nRFgo studio. I am trying to flash the connectivity firmware using the program softdevice tab.
![image](https://user-images.githubusercontent.com/4988857/38391475-efa2bac4-38e9-11e8-821f-a58666a60fa0.png)
I am getting the error as shown in the above screen shot. Next, I try to flash the connectivity firmware using Program Application tab. Now the nRF52 dev kit is getting programmed. Please refer the below screenshot. 
![image](https://user-images.githubusercontent.com/4988857/38391486-f96b37a2-38e9-11e8-8c5e-45fd5178550f.png)
Please refer the last line of the log file. I assume that that the connectivity hex file got flashed as an application firmware. After this, I flash the application firmware in the following path “nRF5_SDK_14.2.0_17b948a\examples\ble_peripheral\ble_app_hrs\pca10040\s132\ses\Output\Debug\Exe”, the development kit gets flashed. Please refer the below screenshot. 
![image](https://user-images.githubusercontent.com/4988857/38391506-03279b14-38ea-11e8-8f6b-36f835a5e7f3.png)
The PC gets connected for some time and then it goes back the paired state. After that the PC shows that the development kit goes back to the paired state. When I run the node command, I get the following error. Please refer the below screenshot. 

![image](https://user-images.githubusercontent.com/4988857/38391517-0bdabafc-38ea-11e8-958c-ddabaec63aeb.png)

**Comment by bihanssen** [comment]
Closing this issue. If you still need assistance or are having problems, please re-post on [DevZone](https://devzone.nordicsemi.com).
