### ISSUE TITLE
Example of how to connect to a peripheral and read the characterisitic

### ISSUE THREAD

**Issue by ksachdeva** [NordicSemiconductor/pc-ble-driver-js#17]
Hi,

Would it be possible to have an example showing how to read the characteristic from a peripheral device ?

Regards & thanks
Kapil

**Comment by kenr** [comment]
Hi, currently we do not have any examples showing how to read the characteristics, but we use this part of the API in a large application we are working on (https://devzone.nordicsemi.com/blogs/801/alpha-090-release-of-new-bluetooth-smart-tool-from/). When the application is released we will improve and expand examples and documentation for the API.

**Comment by ksachdeva** [comment]
Hi,

Created an example repository showing how to use pc-ble-driver-js

https://github.com/ksachdeva/pc-ble-driver-js-examples

Regards
Kapil

**Comment by bihanssen** [comment]
Hi, that's a great initiative. Thanks for sharing.
