### ISSUE TITLE
Using this module on 64 bit Windows

### ISSUE THREAD

**Issue by lilliesAndRoses** [NordicSemiconductor/pc-ble-driver-js#185]
Hello,
I want to use this module on 64-bit windows - for 64 bit Windows environments using electron. I s this simply not supported? I do not see any Windows x64 binaries in the releases either.

I have NRFConnect app installed - which as a part of installation - installed the command line tools as well. Still I am unable to get around the dependency on pc-nrfjprog-js. 
When I try to install it, I get following error

> node scripts/pre-install.js && ( node-pre-gyp install --fallback-to-build=false || node build.js )
Unsupported architecture: x64. On Windows, the nrfjprog libraries currently require 32-bit Node.js.

Is there any way of getting around this? Can I build the nrfjprog tools also from source code for x64 platforms?

Thanks
Amruta

**Comment by bihanssen** [comment]
Hi,
you will need build as 32 bit (use 32 bit node js) until 64 bit support for nrfjprog is in place. There is no problem running a 32 bit build on 64 bit windows, windows supports both architectures side by side.

**Comment by lilliesAndRoses** [comment]
Thanks for the reply.
Is there any timeline about adding support for 64 bit?

**Comment by bihanssen** [comment]
64 bit support is in the pipeline, though priorities may shift. Sometime before end of this year I'd guess.

**Comment by jrobeson** [comment]
I see win32 x64 builds here now: https://github.com/NordicSemiconductor/pc-ble-driver-js/releases

**Comment by lilliesAndRoses** [comment]
True. I think we can close this issue now.
