### ISSUE TITLE
v2.4.3 takes 3x as long to perform full DFU than v2.1.0 on Mojave

### ISSUE THREAD

**Issue by Looveh** [NordicSemiconductor/pc-ble-driver-js#201]
I tried bumping the version I use of this library from 2.1.0 to 2.4.3 and with the newest version a full DFU takes ~280s, while with the older version it takes ~100s. I tried switching back and forth between the versions and this time increase is consistent.

**Comment by bihanssen** [comment]
Closing due to answered.
