### ISSUE TITLE
Unable to execute Notify command using pc-ble-driver-js

### ISSUE THREAD

**Issue by jayakanth459** [NordicSemiconductor/pc-ble-driver-js#208]
Unable to issue notify command to Nordic device from Nodejs

adapter.notifyKeypress(desiredChar.instanceId, 0x00 , (err1, val) => {
                        if (err1) {
                            console.log(`Error enabling notifications on the hrm characteristic: ${err1}.`);
                            console.log(err1)
                            //process.exit(1);
                        }
                        console.log(val);
                        close(adapter)
                    });

**Comment by bihanssen** [comment]
Please use the [Nordic DevZone](http://devzone.nordicsemi.com) portal to report bugs, questions or feedback in general. If you would like to suggest code changes, feel free to submit a pull request.

When reporting, please provide some more context and info about how to reproduce the issue you're seeing.
