### ISSUE TITLE
install failed because of nrf-device-setup

### ISSUE THREAD

**Issue by Nielamu** [NordicSemiconductor/pc-ble-driver-js#210]
Error happened when I deleted node_modules and ran `npm install pc-ble-driver-js --save` today:
`
npm ERR! path D:\codes\mles-pc\node_modules\nrf-device-setup\bin\dfu-trigger.js

npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\codes\mles-pc\node_modules\nrf-device-setup\bin\dfu-trigger.js'
npm ERR! enoent This is related to npm not being able to find a file.
`

Then I noticed that "nrf-device-setup" had a new release 2 days ago.
Is this the reason?

**Comment by bencefr** [comment]
@Nielamu , sorry about this, fix is coming to nrf-device-setup ASAP.
