### ISSUE TITLE
Electron instalation 

### ISSUE THREAD

**Issue by violetgee** [NordicSemiconductor/pc-ble-driver-js#236]
Hello,
I have a problem with the installation. First I run this command in main folder:
npm install -g electron-prebuilt

> These variables can be set in .npmrc file in the root of your Electron based project. Example .npmrc file content:
> runtime = Electron
> target = 1.16.6

I understand that I need to create a file with this extension, right?

> Add the environment variables npm_config_runtime and npm_config_target (must be set for npm install.)

So in env variables:
variables npm_config_runtime   -   npm install
npm_config_target    -   nom install 
?

I checked and have the latest version installed.

When I debug I got this error: 

> Error: Cannot find module 'electron' 

When  I run app electron .\index.js:

> A dynamic link library DLL initialization routine failed.

Also when I run npm rebuil:

> node-pre-gyp ERR! stack Error: Unknown Runtime: 'npm install'

**Comment by datenreisender** [comment]
> Hello,
> I have a problem with the installation. First I run this command in main folder:
> npm install -g electron-prebuilt
> 
> > These variables can be set in .npmrc file in the root of your Electron based project. Example .npmrc file content:
> > runtime = Electron
> > target = 1.16.6
> 
> I understand that I need to create a file with this extension, right?

No, the file name does not just need to have this extension, the whole filename should be `.npmrc`.

Based on your description, I have the impression that you seem quite inexperienced with using npm and building JavaScript/Electron apps. You might need to build up some basic knowledge about that first.

**Comment by violetgee** [comment]
I have already built applications in electron and javascript.
I only have problem adding electron to this project.

**Comment by datenreisender** [comment]
What do you mean with “this project”? `pc-ble-driver-js` or another project using `pc-ble-driver-js`? 

Did creating a [`.npmrc`](https://docs.npmjs.com/files/npmrc) help? 

By the way: `electron-prebuilt` is deprecated, you should not use it anymore.

**Comment by violetgee** [comment]
Ok, thanks for advice :)
I created a new empty electron project and then add there pc-ble-driver-js and thats helped.
Only problem I have now is that I cant debug because I have this error:

> Error: Cannot find module 'electron'

on 
`const` {app, BrowserWindow} = require('electron')

**Comment by violetgee** [comment]
Ok I forgot to add this in launch.json eh

`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Debug Main Process",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
        },
        "args" : ["."],
        "outputCapture": "std"
      }
    ]
  }`

Thank you @datenreisender datenreisender for help!
