### ISSUE TITLE
Support for multiple central links at the same time

### ISSUE THREAD

**Issue by ksachdeva** [NordicSemiconductor/pc-ble-driver-js#29]
Hi,

When I look at the enableBLE() method I do see the option to specify the value for it

https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/10794aac1b6947b72aa57188def3f979d9af568f/api/adapter.js#L321

Would appreciate if you can confirm that multilink central is supported using this library

Regards & thanks
Kapil

**Comment by bihanssen** [comment]
Hi, 
I can confirm that pc-ble-driver supports multiple central links. When in a connection you can start scanning and establish a new connection.
