### ISSUE TITLE
Example app crashing when device found

### ISSUE THREAD

**Issue by vikeri** [NordicSemiconductor/pc-ble-driver-js#52]
For me, the app crashes here: https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/6b1e7ceb42f65b03d25a2bee32b71ac4083030d3/examples/heart_rate_collector.js#L354

`chunk` is `null`.

On macOS Sierra

**Comment by bihanssen** [comment]
Thanks for reporting.
I was able to reproduce and fix the bug.

**Comment by vikeri** [comment]
Sweet! 🎉
