### ISSUE TITLE
Suggestion: Consider using prettier to format the code?

### ISSUE THREAD

**Issue by vikeri** [NordicSemiconductor/pc-ble-driver-js#55]
I know you use eslint but to me [prettier](https://github.com/prettier/prettier) provides a better, more unified experience. Totally understand that this is a somewhat political decision and that it may or may not suit NS.

**Comment by bihanssen** [comment]
Prettier is quite nice in it's simplicity, so it's something we will probably consider at some point. Thanks for the input.
