### ISSUE TITLE
Released/tagged version 2.0.0 points to submodule pc-ble-driver branch master

### ISSUE THREAD

**Issue by kenr** [NordicSemiconductor/pc-ble-driver-js#74]
https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/3887f82a35dd0b05e82e370db672971ae388ead9/.gitmodules#L4

Released/tagged version should not point to pc-ble-driver master branch. It should point to a tagged version in pc-ble-driver.

**Comment by bihanssen** [comment]
Agreed, will fix it.

**Comment by mrodem** [comment]
Fixed by #83.
