### ISSUE TITLE
Change device connection timeout not to be an error

### ISSUE THREAD

**Issue by kenr** [NordicSemiconductor/pc-ble-driver-js#88]
I think it would be better if device connection timeout did not generate an error in the callback.
The error should be reserved for other events like communication error with the adapter.

https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/749089aa7c0cfbb240adc134fb0844c0fd8f3ae3/api/adapter.js#L1058

**Comment by bihanssen** [comment]
The timeout should be reported somewhere, or don't you think it's important info? One could argue that the absence of the connected-event is enough info that the connection didn't occur.

**Comment by kenr** [comment]
device connection timeout is an event that is sent:
https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/749089aa7c0cfbb240adc134fb0844c0fd8f3ae3/api/adapter.js#L1054

**Comment by bihanssen** [comment]
I'm quite sure we could remove the error callback on timeout in connect without causing problems.

**Comment by mrodem** [comment]
Done in #111.
