### ISSUE TITLE
New driver often give NRF_ERROR_INTERNAL when calling enableBLE

### ISSUE THREAD

**Issue by kenr** [NordicSemiconductor/pc-ble-driver-js#97]
Kit: PCA100028
nrfjprog version: 9.6.0
JLinkARM.dll version: 6.16e

Error: NRF_ERROR_INTERNAL (0x3)

Get the same error on PCA100040.

**Comment by bihanssen** [comment]
Updated connectivity hex, addressing the issue, was included in v2.1.1.
